---
- block:
    - name: Adjust dhcpd.conf(5)
      template:
        src: "{{ inventory_hostname }}/dhcpd.conf.j2"
        dest: /etc/dhcpd.conf
        mode: 0640
        owner: root
        group: wheel
        backup: yes
        validate: /usr/sbin/dhcpd -n -c %s
      notify: reload dhcpd config

    - name: Ensure if dhcpd service is started and enabled in rc.conf(8)
      service: name=dhcpd state=started enabled=yes arguments="{{ dhcpd_interfaces | mandatory | join(' ') }}"
      notify: reload dhcpd config

  when: dhcpd|bool == true
  become: true
  tags: dhcpd

- name: Ensure if dhcpd is stopped and disabled in rc.conf(8)
  become: true
  service: name=dhcpd state=stopped enabled=no
  when: dhcpd|bool == false
  tags: dhcpd