---
- name: change hostname
  shell: hostname $(cat /etc/myname)

- name: set default route
  shell: route delete default; route add default {{ mygate }}

- name: change interfaces
  reboot:

- name: remove default route
  shell: route delete default

- name: reload bgpd config
  shell: bgpctl reload

- name: reload ospfd config
  shell: ospfctl reload

- name: reload dhcpd config
  service: name=dhcpd state=restarted enabled=yes arguments="{{ dhcpd_options | mandatory }}"

- name: reload iked config
  service: name=iked state=restarted enabled=yes

- name: flush the SPD and the SAD
  shell: ipsecctl -Fd
  listen: "restart ipsec"

- name: reload isakmpd
  service: name=isakmpd state=restarted enabled=yes args=-4K
  listen: "restart ipsec"

- name: restart ipsec config
  shell: ipsecctl -f /etc/ipsec.conf
  listen: "restart ipsec"

- name: reload pf config
  raw: pfctl -f /etc/pf.conf

- name: restart snmpd
  service: name=snmpd state=restarted enabled=true

- name: restart ntpd
  service: name=ntpd state=restarted enabled=true
